03_Django/CRUD_COPY/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'), # GET
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'), # GET(new), POST(crete)
    path('<int:article_pk>/', views.detail, name='detail'), # GET
    path('<int:article_pk>/delete/', views.delete, name='delete'), # POST
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'), # GET(edit), POST(update)
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update'),
]

03_Django/CRUD_COPY/crud/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('jobs/', include('jobs.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_Django/CRUD_COPY/jobs/urls.py
from django.urls import path 
from . import views 

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

03_Django/CRUD_COPY/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'제목: {self.title}, 내용: {self.content}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk', ]

    def __str__(self):
        # return f'댓글: {self.content}'
        return f'<Article({self.article_id}): Comment({self.pk} - {self.content})>'

03_Django/CRUD_COPY/jobs/models.py
from django.db import models

class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    def __str__(self):
        return self.name 

03_Django/CRUD_COPY/articles/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from .models import Article, Comment
from IPython import embed

def index(request):
    # articles = Article.objects.all()[::-1]
    articles = Article.objects.order_by('-pk')
    # print(articles)
    # print(type(articles))
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)

def create(request):
    # POST 요청일 때
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article(title=title, content=content)
        article.save()
        return redirect('articles:detail', article.pk)
    # GET 요청일 때
    else:
        return render(request, 'articles/create.html')
    """
    title = request.POST.get('title')
    # print(title)
    content = request.POST.get('content')

    #1. 첫번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    #2. 두번째 방법
    article = Article(title=title, content=content)
    article.save()

    #3. 세번째 방법
    # Article.objects.create(title=title, content=content)

    return redirect(f'/articles/{article.pk}/')
    """
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    # comments = Comment.objects.all()
    comments = article.comments.all()
    context = {'article': article, 'comments': comments, }
    # embed()
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', article.pk)

def update(request, article_pk):
    # embed()
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        context = {'article': article}
        return render(request, 'articles/update.html', context)

def comments_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment(article=article, content=content)
        comment.save()
        return redirect('articles:detail', article.pk)
    else:
        return redirect('articles:detail', article.pk)

def comments_delete(request, article_pk, comment_pk):
    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
    return redirect('articles:detail', article_pk)

def comments_update(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('articles:detail', article_pk)
    else:
        context = {'comment': comment}
        return render(request, 'articles/comment_update.html', context)

03_Django/CRUD_COPY/jobs/views.py
from django.shortcuts import render
from .models import Job
from faker import Faker
from decouple import config 
import requests
from pprint import pprint

def index(request):
    return render(request, 'jobs/index.html')

def past_life(request):
    name = request.POST.get('name')
    person = Job.objects.filter(name=name).first()

    # DB에 이름이 있을 경우
    if person:
        past_job = person.past_job
    # DB에 이름이 없을 경우
    else:
        fake = Faker()
        # 랜덤 직업 생성
        past_job = fake.job()
        # 새로운 이름, 직업 추가 후 DB 저장
        person = Job(name=name, past_job=past_job)
        person.save()
    
    # GIPHY
    #1. API key 가져오기 
    GIPHY_API_KEY = config('GIPHY_API_KEY')
    #2. 요청 URL 세팅 
    url = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API_KEY}&q={past_job}&limit=1&lang=ko'
    #3. 실제 요청을 보내자. (json -> dict)
    data = requests.get(url).json()
    #4. image 추출 
    try:
        image = data.get('data')[0].get('images').get('original').get('url')
    except IndexError:
        image = None

    # NAVER IMAGE
    #1. 요청 헤더 정보 준비
    NAVER_ID = config('NAVER_ID')
    NAVER_SECRET = config('NAVER_SECRET')

    headers = {
        'X-Naver-Client-Id': NAVER_ID,
        'X-Naver-Client-Secret': NAVER_SECRET 
        }
    #2. 요청 URL 준비 
    naver_url = f'https://openapi.naver.com/v1/search/image?query={past_job}&filter=medium&display=1'

    #3. 실제 요청 보내기
    naver_data = requests.get(naver_url, headers=headers).json()
    # pprint(naver_data)

    #4. 이미지 링크 추출하기 
    naver_image = naver_data.get('items')[0].get('link')
    
    context = {'person': person, 'image': image, 'naver_image': naver_image}

    return render(request, 'jobs/past_life.html', context)

03_Django/CRUD_COPY/articles/templates/articles/comment_update.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">Comment Update</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="">COMMENT UPDATE</label><br>
        <input type="text" name="content" value="{{ comment.content }}"><br>
        <input type="submit" value="댓글 수정" class="btn btn-primary">
    </form>
{% endblock %}

03_Django/CRUD_COPY/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">NEW</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title"><br>
        <label for="content">Content</label>
        <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
        <input type="submit" value="글 작성">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}

03_Django/CRUD_COPY/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">DETAIL</h2>
    <h3>{{ article.pk }}번째 글</h3>
    <hr>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <p>글 생성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
    <p>글 수정 시각: {{ article.updated_at|date:"M, j, Y" }}</p>
    <hr>

    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
        {% csrf_token %}
        <label for="content">COMMENT</label><br>
        <input type="text" name="content" id="content"><br>
        <input type="submit" value="댓글 작성" class="btn btn-warning">
    </form>
    <hr>
    <p><b>{{ comments|length }}개의 댓글</b></p>
    <hr>
    <p><b>댓글 목록</b></p>
    {% for comment in comments %}
        <li>{{ comment.content }}</li>
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="댓글 삭제" class="btn btn-danger">
        </form>
        <a href="{% url 'articles:comments_update' article.pk comment.pk%}">[댓글 수정]</a>

        </form>
    {% empty %}
        <p><b>댓글이 없네유....댓글 좀 써주세유..</b></p>
    {% endfor %}
    <hr>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글 삭제" class="btn btn-primary">
    </form>
    <a href="{% url 'articles:update' article.pk %}">[글 수정]</a><br>
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}

03_Django/CRUD_COPY/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">Articles</h2>
    {% for article in articles %}
        <p>글 번호: {{ article.id }}</p>
        <p>글 제목: {{ article.title }}</p>
        <a href="{% url 'articles:detail' article.pk %}">[상세 글]</a>
        <hr>
    {% endfor %}
    <a href="{% url 'articles:create' %}">[글 작성]</a>
{% endblock %}

03_Django/CRUD_COPY/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">EDIT</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title" value="{{ article.title }}"><br>
        <label for="content">Content</label>
        <textarea name="content" id="content" cols="30" rows="5">{{ article.content }}</textarea><br>
        <input type="submit" value="글 수정">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}

03_Django/CRUD_COPY/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h1 class="text-center">CRUD</h1>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

03_Django/CRUD_COPY/jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block body %}
    <h1 class="text-center">전생의 직업은..?</h1>
    <h2 class="text-center">당신의 전생 직업을 알려드립니다.</h2>
    <hr>
    
    <form action="{% url 'jobs:past_life' %}" method="POST">
        {% csrf_token %}
        <label for="name">NAME</label><br>
        <input type="text" name="name" id="name"><br>
        <input type="submit" value="이름 전송">
    </form>
{% endblock %}

03_Django/CRUD_COPY/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">{{ person.name }}님의 전생 직업은 {{ person.past_job }}</h2>
    <h3 class="text-center">GIPHY</h3>
    <img src="{{ image }}" alt="giphy-image">

    <h3 class="text-center">NAVER IMAGE</h3>
    <img src="{{ naver_image }}" alt="naver-image">
    <a href="{% url 'jobs:index' %}">내 전생의 직업이 또 있을까?</a>
{% endblock %}