03_Django/09_django_axios/accounts/urls.py
from django.urls import path 
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
]

03_Django/09_django_axios/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
]

03_Django/09_django_axios/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_Django/09_django_axios/articles/models.py
from django.db import models
from django.conf import settings 

class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_articles", blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    class Meta:
        ordering = ('-pk', )
    
    def __str__(self):
        return self.title 

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk', )
    
    def __str__(self):
        return self.content

03_Django/09_django_axios/articles/forms.py
from django import forms 
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=10,
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title',
                'placeholder': 'Enter the title',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-content',
                'placeholder': 'Enter the content',
                'rows': 5,
                'cols': 50,
            }
        )
    )
    class Meta:
        model = Article 
        fields = ('title','content', )

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )



# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=20,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'my-title',
#                 'placeholder': 'Enter the title!',
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': 'Enter the content!',
#                 'rows': 5,
#                 'cols': 50,
#             }
#         )
#     )

03_Django/09_django_axios/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
import hashlib
from IPython import embed

def index(request):
    #1. session 정보에서 visits_num 이라는 키로 접근해 값을 가져옴
    # 해당하는 키가 없으면 0을 가져옴
    visits_num = request.session.get('visits_num', 0)
    #2. 가져온 값을 session에 'visits_num' 이라는 새로운 키의 값으로 1씩 증가
    request.session['visits_num'] = visits_num + 1
    #3. session data를 수정하면 장고는 수정한 내용을 알 수 없어서 작성하는 코드
    request.session.modified = True 
    # embed()

    articles = Article.objects.all()
    context = {'articles': articles, 'visits_num': visits_num, }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    """
    Form Class
    모델에 대한 정보를 알지 못해서 유효성 검사 이후에 cleaned_data를 통해 데이터 정제 후 
    DB에 실제 저장하는 로직 필요

    Model Form
    이미 Model에 대한 정보(스키마)를 알고 있기 때문에 어떤 모델에 레코드를 넣어야 하는지 알고 있음.
    form.save()만 해도 DB에 저장됨
    """
    if request.method == 'POST':
        # form 인스턴스를 생성하고 요청에 의한 데이터로 채운다.
        form = ArticleForm(request.POST)
        # 해당 폼이 유효한지 확인
        if form.is_valid():
            article = form.save(commit=False)
            article.user_id = request.user.id
            article.save()
            #1. content를 공백 기준으로 리스트로 변경후 for문 
            for word in article.content.split():
                #2. '#'으로 시작하는 요소를 선택
                if word.startswith('#'):
                    #3. word랑 같은 해시 태그를 찾고 있으면 
                    # 기존 객체를 없으면 새로운 객체 생성
                    hashtag, created = Hashtag.objects.get_or_create(content=word)
                    #4. 게시글의 해시태그 목록에 해당 단어를 추가 
                    article.hashtags.add(hashtag)
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
        # embed()
    context = {'form': form,}
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    person = get_object_or_404(get_user_model(), pk=article.user.pk)
    comment_form = CommentForm()
    context = {
        'article': article, 
        'comment_form': comment_form, 
        'comments': comments,
        'person': person,
        }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.user:
            article.delete()
    return redirect('articles:index') # redirect -> GET 요청

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            # instance-> 수정의 대상이 되는 특정한 글 객체
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                article.hashtags.clear()
                for word in article.content.split():
                    if word.startswith('#'):
                        hashtag, created = Hashtag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')

    context = {'form': form, 'article': article, }
    return render(request, 'articles/form.html', context)

"""
* CREATE & UPDATE는 html 파일 공유

Create 로직
1. GET
- 사용자가 데이터를 입력 할 수 있는 빈 Form을 제공
2. POST
- 사용자가 보낸 새로운 글을 DB에 저장

Update 로직
1. GET 
- 기존 사용자의 글이 입력된 Form 제공
2. POST
- 수정된 글을 DB에 저장
"""

@require_POST
def comments_create(request, article_pk):
    # article = get_object_or_404(Article, pk=article_pk)
    if request.user.is_authenticated:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.article_id = article_pk
            comment.save()
    return redirect('articles:detail', article_pk)

@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)

@login_required
def like(request, article_pk):
    if request.is_ajax():
        article = get_object_or_404(Article, pk=article_pk)
        user = request.user

        #1. 해당 게시글에 좋아요를 누른 사람들 중에서 user.pk(현재 요청 유저)를 가진 user가 존재하면
        if article.like_users.filter(pk=user.pk).exists():
            # 좋아요 취소
            article.like_users.remove(user)
            liked = False
        #2. 존재하지 않는다면 좋아요를 누른 유저 목록에 유저 추가
        else:
            # 좋아요 누름
            article.like_users.add(user)
            liked = True
        context = {
            'liked': liked,
            'count': article.like_users.count(),
            }
        return JsonResponse(context)
    else:
        return HttpResponseBadRequest()

@login_required
def follow(request, article_pk, user_pk):
    # 게시글을 작성한 유저
    person = get_object_or_404(get_user_model(), pk=user_pk)
    # 접속 유저(해당 함수로 요청을 보낸 사람)
    user = request.user 

    # 해당 person의 팔로워 중에서 이 함수를 요청한 유저가 존재하면
    if person.followers.filter(pk=user.pk).exists():
        # 언팔로우
        person.followers.remove(user)
    # 존재하지 않다면
    else:
        # 팔로우
        person.followers.add(user)
    return redirect('articles:detail', article_pk)

@login_required
def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    articles = hashtag.article_set.order_by('-pk')
    context = {'hashtag': hashtag, 'articles': articles, }
    return render(request, 'articles/hashtag.html', context)
    

03_Django/09_django_axios/articles/templates/articles/_article.html
<div class="card">
    <h5 class="card-header">
        글 작성자: <a href="{% url 'accounts:profile' article.user.username %}" class="card-link">{{ article.user }}</a>
    </h5>
    <div class="card-body">
        <h5 class="card-title">글 제목: {{ article.title }}</h5>
        <p>글 번호: {{ article.pk }}</p>
        <p class="card-text">
            <span id="like-count-{{ article.pk }}" class="card-text">{{ article.like_users.count }}</span>명이 이 글을 좋아합니다.
            <i class="{% if user in article.like_users.all %}
            fas
            {% else %}
            far
            {% endif %}  fa-heart like-button"
            data-id="{{ article.pk }}"
            style="color:crimson"
            >
            </i>
        </p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">글 상세보기</a>
    </div>
</div>

03_Django/09_django_axios/articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
    <p class="lead mb-1">작성자 정보</p>
    <h1 class="display-4">{{ person.username }}</h1>
    <hr>
    <p class="lead">
        팔로잉: {{ person.followings.all|length }} | 팔로워: {{ person.followers.all|length }}
    </p>
    {% if user != article.user %}
        {% if user in person.followers.all %}
            <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">Unfollow</a>
        {% else %}
            <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">Follow</a>
        {% endif %}
    {% endif %}
    
</div>

03_Django/09_django_axios/articles/templates/articles/_nav.html
{% load gravatar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'articles:index' %}">
        <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=30&d=robohash" class="d-inline-block align-top" alt="gravatar">
        Hello, {{ user.username }} 
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:profile' user.username %}">PROFILE</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:update' %}">USER UPDATE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:change_password' %}">CHANGE PASSWORD</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
            </li>
            <li class="nav-item">
                <form action="{% url 'accounts:delete' %}" method="POST" style="display:inline;">
                    {% csrf_token %}
                    <input type="submit" value="회원탈퇴" class="btn btn-danger">
                </form>
            </li>
        </ul>
    </div>

    {% else %}

    <a class="navbar-brand" href="{% url 'articles:index' %}">
        <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=30&d=robohash" class="d-inline-block align-top" alt="gravatar">
        Hello, Stranger
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
            </li>
        </ul>
    </div>
    {% endif %}
</nav>

03_Django/09_django_axios/articles/templates/articles/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/caed28bd65.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    {% bootstrap_css %}
    <style>
        div > h3 {
            color: blueviolet;
        }
    </style>
    <title>Document</title>
</head>
<body>
    {% include "articles/_nav.html" %}
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

03_Django/09_django_axios/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load make_link %}

{% block body %}
    <h2>DETAIL</h2>
    <hr>
    {% include "articles/_follow.html" %}
    <hr>
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article|hashtag_link|safe }}</p>
    <p>글 생성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
    <p>글 수정 시각: {{ article.updated_at|date:"M, j, Y" }}</p>
    <hr>
    <p>댓글 작성</p>
    {% if user.is_authenticated %}
        <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <input type="submit" value="댓글 작성" class="btn btn-dark">
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인 해주세요.]</a>
    {% endif %}

    <hr>
    <p><b>댓글 목록</b></p>
    <p><b>현재까지 댓글 수: {{ comments.count }}</b></p>
    {% for comment in comments %}
        <div>
            <p><b>댓글 작성자: {{ comment.user }}</b></p>
            <p>댓글:{{ forloop.revcounter }} : {{ comment.content }}</p>
            {% if request.user == comment.user %}
                <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="댓글 삭제" class="btn btn-warning">
                </form>
            {% endif %}
        </div>
    {% empty %}
        <p><b>댓글이 없네유 ㅠㅠ</b></p>
    {% endfor %}
    <hr>
    {% if request.user == article.user %}
        <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="글 삭제">
        </form>
        <a href="{% url 'articles:update' article.pk %}">[글 수정]</a>
    {% endif %}
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}

03_Django/09_django_axios/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
        <h2>CREATE</h2>
    {% else %}
        <h2>UPDATE</h2>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit="Submit" reset="Cancel" %}{% endbuttons %}
    </form>

    {% if request.resolver_match.url_name == 'create' %}
        <a href="{% url 'articles:index' %}">[메인 페이지]</a>
    {% else %}
        <a href="{% url 'articles:detail' article.pk %}">[글 상세보기]</a>
    {% endif %}
{% endblock %}

03_Django/09_django_axios/articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}
{% block body %}
<div class="jumbotron jumbotron-fluid text-center text-white bg-dark my-2">
    <div class="container">
        <h1 class="display-4 text-center">{{ hashtag.content }}</h1>
        <p class="lead">{{ articles|length }}개의 게시글</p>
    </div>
</div>

<hr>

<h3 class="text-center">{{ hashtag.content }}(을)를 태그한 글</h3>
<div class="row">
    {% for article in articles %}
        {% with likes=article.like_users.all comments=article.comment_set.all %}
        <div class="col-4 my-2">
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text">{{ article.content }}</p>
            <p class="card-text">{{ likes|length }}명이 좋아요!</p>
            <p class="card-text">{{ comments|length }}개의 댓글!</p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">상세글 보러가기</a>
            </div>
        </div>
        </div>
        {% endwith %}
    {% endfor %}
  </div>
{% endblock %}

03_Django/09_django_axios/articles/templates/articles/index.html
{% extends 'articles/base.html' %}

{% block body %}
    <h1>Articles</h1>
    <p><b>{{ request.user.username }}님의 방문 횟수: {{ visits_num }}{% if visits_num == 1 %} time{% else %} times{% endif %}</b></p>
    {% for article in articles %}
        {% include "articles/_article.html" %}
    {% endfor %}
    {% if user.is_authenticated %}
        <a href="{% url 'articles:create' %}">[글 작성]</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인 해주세요]</a>
    {% endif %}
    <script>
        const likeButtons = document.querySelectorAll('.like-button')
        likeButtons.forEach(button => {
            button.addEventListener('click', function(event) {
                console.log(event)
                //1. event.target.dataset.id는 아이콘 태그의 data-id로 지정한 값
                const articleId = event.target.dataset.id
                // XHR 요청을 확인하는 것은 요청 정보 내에 HTTP_X_REQUESTED_WITH header에 XMLHttpRequest 객체 값이 있어야 한다.
                axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
                axios.defaults.xsrfCookieName = 'csrftoken'
                axios.defaults.xsrfHeaderName = 'X-CSRFToken'
                //2. 해당 상세 게시글에 좋아요를 누르는 요청을 보내자
                axios.post(`/articles/${articleId}/like/`)
                //3. 응답을 확인하자!!
                .then(response => {
                    console.log(response)
                    document.querySelector(`#like-count-${articleId}`).innerText = response.data.count
                    if (response.data.liked) {
                        event.target.classList.remove('far')
                        event.target.classList.add('fas')
                    } else {
                        event.target.classList.remove('fas')
                        event.target.classList.add('far')
                    }
                })
                .catch(error => console.log(error))
            })
        })
    </script>
{% endblock %}